---
# This role will run a CouchDB server on the db group

- name: check if db credentials are valid for CouchDB
  fail: msg="The db provider in your {{ inventory_dir }}/group_vars/all is {{ db_provider }}, it has to be CouchDB, pls double check"
  when: db_provider != "CouchDB"

- name: ensure couchdb config directory exists
  file:
    path: "{{ db_config_dir }}"
    state: directory

- name: copy template from local to remote (which is really local) and fill in templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ db_config_dir }}/{{ item }}"
  with_items:
    - admins.ini
    - query_server.ini

- name: create configmap
  shell: "kubectl create configmap couchdb-config --from-file={{ db_config_dir }}/query_server.ini"
  ignore_errors: yes

- name: create secrets
  shell: "kubectl create secret generic couchdb-admins --from-file={{ db_config_dir }}//admins.ini"
  ignore_errors: yes

- name: create db pod
  shell: "kubectl apply -f {{kube_pod_dir}}/db.yml"

- name: wait until the CouchDB in this host is up and running
  wait_for:
    delay: 2
    host: "{{ db_host }}"
    port: "{{ db_port }}"
    timeout: 60
