apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx_service_name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ template "nginx_service_name" . }}
spec:
  type: NodePort
  selector:
    name: {{ template "nginx_deployment_name" . }}
  ports:
    - port: {{ template "nginx_http_port" . }}
      targetPort: {{ template "nginx_http_port" . }}
      {{- if .Values.httpNodePort }}
      nodePort: {{ .Values.httpNodePort }}
      {{- end }}
      name: http
    - port: {{ template "nginx_https_port" . }}
      targetPort: {{ template "nginx_https_port" . }}
      {{- if .Values.httpsNodePort }}
      nodePort: {{ .Values.httpsNodePort }}
      {{- end }}
      name: https-api
    - port: {{ template "nginx_https_admin_port" . }}
      targetPort: {{ template "nginx_https_admin_port" . }}
      {{- if .Values.httpsAdminNodePort }}
      nodePort: {{ .Values.httpsAdminNodePort }}
      {{- end }}
      name: https-admin
