# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# There are some variables that a user must define for their deployment.
# Check for those values here and attempt to give helpful error messages.
#
# whisk.ingress.type is {{ required "You must provide a value for whisk.ingress.type (See docs/ingress.md)" .Values.whisk.ingress.type }}
# whisk.ingress.api_host_name is {{ required "You must provide a value for whisk.ingress.api_host_name (See docs/ingress.md)" .Values.whisk.ingress.api_host_name }}
# whisk.ingress.api_host_port is {{ required "You must provide a value for whisk.ingress.api_host_port (See docs/ingress.md)" .Values.whisk.ingress.api_host_port }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whisk.config
  namespace: {{ .Release.Namespace | quote }}
data:
  whisk_info_date: {{ dateInZone "2006-01-02-03:04:05Z" (now) "UTC"| quote }}
  whisk_info_buildNo: {{ .Values.whisk.versions.tag | quote }}
  whisk_cli_version_tag: {{ .Values.whisk.versions.cli | quote }}
  whisk_system_namespace: {{ .Values.whisk.systemNameSpace | quote }}
  whisk_api_host_proto: {{ .Values.whisk.ingress.api_host_proto | quote }}
  whisk_api_host_port: {{ .Values.whisk.ingress.api_host_port | quote }}
  whisk_api_host_name: {{ .Values.whisk.ingress.api_host_name | quote }}
  whisk_api_host_nameAndPort: "{{ .Values.whisk.ingress.api_host_name }}:{{ .Values.whisk.ingress.api_host_port }}"
  whisk_api_host_url: "{{ .Values.whisk.ingress.api_host_proto }}://{{ .Values.whisk.ingress.api_host_name }}:{{ .Values.whisk.ingress.api_host_port }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db.config
  namespace: {{ .Release.Namespace | quote }}
data:
  db_prefix: {{ .Values.db.dbPrefix | quote }}
  db_protocol: {{ .Values.db.protocol | quote }}
  db_provider: {{ .Values.db.provider | quote }}
  db_host: {{ include "db_host" . | quote }}
  db_port: {{ .Values.db.port | quote }}
  db_url: "{{ .Values.db.protocol }}://{{ include "db_host" . }}:{{ .Values.db.port }}"
  db_host_port: "{{ include "db_host" . }}:{{ .Values.db.port }}"
  db_whisk_actions: {{ .Values.db.actionsTable | quote }}
  db_whisk_activations: {{ .Values.db.activationsTable | quote }}
  db_whisk_auths: {{ .Values.db.authsTable | quote }}
