# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controller.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Values.controller.name | quote }}
spec:
  selector:
    name: {{ .Values.controller.name | quote }}
  ports:
    - port: {{ .Values.controller.port }}
      name: http
