# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    name: {{ .Release.Name }}-controller
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  selector:
    name: {{ .Release.Name }}-controller
  ports:
    - port: {{ .Values.controller.port }}
      name: http
