# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if not .Values.db.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name | quote }}
  labels:
    name: {{ .Values.db.name | quote }}
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  selector:
    name: {{ .Values.db.name | quote }}
  ports:
    - port: {{ .Values.db.port }}
      name: couchdb
{{ end }}
