{{- if .Values.elasticsearch.esConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-elasticsearch-cm
  labels:
{{ include "openwhisk.label_boilerplate" .| indent 4 }}
data:
{{- range $path, $config := .Values.elasticsearch.esConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
