{{- if .Values.elasticsearch.rbac.create -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      {{- if eq .Values.elasticsearch.podSecurityPolicy.name "" }}
      - {{ $fullName | quote }}
      {{- else }}
      - {{ .Values.elasticsearch.podSecurityPolicy.name | quote }}
      {{- end }}
    verbs:
      - use
{{- end -}}
