{{- if and .Values.elasticsearch.podSecurityPolicy.create (not .Values.elasticsearch.external) (eq .Values.activationStoreBackend "ElasticSearch") }}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ default $fullName .Values.elasticsearch.podSecurityPolicy.name | quote }}
  labels:
{{ include "openwhisk.label_boilerplate" .| indent 4 }}
spec:
{{ toYaml .Values.elasticsearch.podSecurityPolicy.spec | indent 2 }}
{{- end -}}
