---
{{- if and .Values.pdb.enable (not .Values.elasticsearch.external) (eq .Values.activationStoreBackend "ElasticSearch") }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-elasticsearch-pdb
  labels:
{{ include "openwhisk.label_boilerplate" .| indent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.elasticsearch.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-elasticsearch
{{- end }}
