# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: ConfigMap
metadata:
  name: install-packages-cm
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
data:
{{ (.Files.Glob "configMapFiles/installPackages/myTask.sh").AsConfig | indent 2 }}
