# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-invoker-scripts
  labels:
{{ include "openwhisk.label_boilerplate" .| indent 4 }}
data:
{{ (.Files.Glob "configMapFiles/dockerPullRuntimes/playbook.yml").AsConfig | indent 2 }}
{{ (.Files.Glob "configMapFiles/configureDNS/configureDNS.sh").AsConfig | indent 2 }}
