# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if not .Values.kafka.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name | quote }}
  labels:
    name: {{ .Values.kafka.name | quote }}
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  ports:
  - name: broker
    port: {{ .Values.kafka.port }}
  selector:
    name: {{ .Values.kafka.name | quote }}
{{- end }}
