# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db.config
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
data:
  db_prefix: {{ .Values.db.dbPrefix | quote }}
  db_protocol: {{ .Values.db.protocol | quote }}
  db_provider: {{ .Values.db.provider | quote }}
  db_host: {{ include "openwhisk.db_host" . | quote }}
  db_port: {{ .Values.db.port | quote }}
  db_url: "{{ .Values.db.protocol }}://{{ include "openwhisk.db_host" . }}:{{ .Values.db.port }}"
  db_host_port: "{{ include "openwhisk.db_host" . }}:{{ .Values.db.port }}"
  db_whisk_actions: {{ .Values.db.actionsTable | quote }}
  db_whisk_activations: {{ .Values.db.activationsTable | quote }}
  db_whisk_auths: {{ .Values.db.authsTable | quote }}
