# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{- if ne .Values.docker.registry.name "" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-private-registry.auth
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "openwhisk.dockerRegistrySecret" . }}
{{- end }}

