# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# Core pods are allowed to have view access to k8s APIs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: ow-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-view
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: ow-core
    namespace: {{ .Release.Namespace | quote }}


{{ if eq .Values.invoker.containerFactory.impl "kubernetes" }}
# When using KubernetesContainerFactory, invoker pods need extensive
# permissions to manage pods and deployments. The ability to create
# pods can enable privilege escalation attacks, so restrict it to a
# ServiceAccount that is only used for the invokers and only defined
# when using KubernetesContainerFactory.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.invoker.name | quote }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.invoker.name | quote }}
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.invoker.name | quote }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.invoker.name | quote }}
roleRef:
  kind: Role
  name: {{ .Values.invoker.name | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
