# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
  labels:
    name: {{ .Release.Name }}-zookeeper
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  selector:
    name: {{ .Release.Name }}-zookeeper
  clusterIP: None
  ports:
    - port: {{ .Values.zookeeper.port }}
      name: "zookeeper"
    - port: {{ .Values.zookeeper.serverPort }}
      name: "server"
    - port: {{ .Values.zookeeper.leaderElectionPort }}
      name: "leader-election"
