# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if and (not .Values.zookeeper.external) (and .Values.k8s.persistence.enabled (eq (int .Values.zookeeper.replicaCount) 1 )) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{- .Values.zookeeper.persistence.pvcName -}}-data"
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
{{- if .Values.k8s.persistence.useDynamicProvisioning }}
  storageClassName: {{ .Values.k8s.persistence.defaultStorageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}
{{- end }}
