# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if not .Values.zookeeper.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name | quote }}
  labels:
    name: {{ .Values.zookeeper.name | quote }}
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  selector:
    name: {{ .Values.zookeeper.name | quote }}
  clusterIP: None
  ports:
    - port: {{ .Values.zookeeper.port }}
      name: "zookeeper"
    - port: {{ .Values.zookeeper.serverPort }}
      name: "server"
    - port: {{ .Values.zookeeper.leaderElectionPort }}
      name: "leader-election"
{{- end }}
