# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
{{ if not .Values.zookeeper.external }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Values.zookeeper.name | quote }}
spec:
  selector:
    name: {{ .Values.zookeeper.name | quote }}
  clusterIP: None
  ports:
    - port: {{ .Values.zookeeper.port }}
      name: "zookeeper"
    - port: {{ .Values.zookeeper.serverPort }}
      name: "server"
    - port: {{ .Values.zookeeper.leaderElectionPort }}
      name: "leader-election"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zookeeper.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  zoo.cfg: |
    tickTime={{ .Values.zookeeper.config.tickTime }}
    clientPort={{ .Values.zookeeper.port }}
    initLimit={{ .Values.zookeeper.config.initLimit }}
    syncLimit={{ .Values.zookeeper.config.syncLimit }}
    dataDir={{ .Values.zookeeper.config.dataDir }}
    dataLogDir={{ .Values.zookeeper.config.dataLogDir }}
{{- $zkname := .Values.zookeeper.name }}
{{- $zkserverport := .Values.zookeeper.serverPort }}
{{- $zkelectionport := .Values.zookeeper.leaderElectionPort }}
{{- range $i, $e := until (int .Values.zookeeper.replicaCount) }}
    server.{{ . }}={{ $zkname }}-{{ . }}.{{ $zkname }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $zkserverport }}:{{ $zkelectionport }}
{{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.zookeeper.name | quote }}
  namespace: {{ .Release.Namespace | quote}}
spec:
  serviceName: {{ .Values.zookeeper.name | quote }}
  podManagementPolicy: "Parallel"
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.zookeeper.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.zookeeper.name | quote }}
    spec:
      restartPolicy: {{ .Values.zookeeper.restartPolicy | quote }}

{{- if .Values.affinity.enabled }}
      affinity:
{{ include "affinity.core" . | indent 8 }}
{{ include "affinity.selfAntiAffinity" ( .Values.zookeeper.name | quote ) | indent 8 }}
{{- end }}

      volumes:
        - name: zk-config
          configMap:
            name: {{ .Values.zookeeper.name | quote }}

      containers:
      - name: {{ .Values.zookeeper.name | quote }}
        image: {{ .Values.zookeeper.image | quote }}
        imagePullPolicy: {{ .Values.zookeeper.imagePullPolicy | quote }}
        command: ["/bin/bash", "-c", "hostname -s | cut -d'-' -f2 > {{ .Values.zookeeper.config.dataDir }}/myid; cat {{ .Values.zookeeper.config.dataDir }}/myid; cat /conf/zoo.cfg; zkServer.sh start-foreground"]
        ports:
        - name: zookeeper
          containerPort: {{ .Values.zookeeper.port }}
        - name: server
          containerPort: {{ .Values.zookeeper.serverPort }}
        - name: leader-election
          containerPort: {{ .Values.zookeeper.leaderElectionPort }}

        volumeMounts:
        - mountPath: /conf
          name: zk-config
{{- if .Values.zookeeper.persistence.enabled }}
        - mountPath: {{ .Values.zookeeper.config.dataDir }}
          name: "{{- .Values.zookeeper.persistence.pvcName -}}-data"
        - mountPath: {{ .Values.zookeeper.config.dataLogDir }}
          name: "{{- .Values.zookeeper.persistence.pvcName -}}-datalog"
{{- end }}

{{- if .Values.zookeeper.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: "{{- .Values.zookeeper.persistence.pvcName -}}-data"
    spec:
      storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
      accessModes:
        - {{ .Values.zookeeper.persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.zookeeper.persistence.size }}
  - metadata:
      name: "{{- .Values.zookeeper.persistence.pvcName -}}-datalog"
    spec:
      storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
      accessModes:
        - {{ .Values.zookeeper.persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.zookeeper.persistence.size }}
{{- end }}
{{- end }}
