# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apigw.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Values.apigw.name | quote }}
spec:
  selector:
    name: {{ .Values.apigw.name | quote }}
  ports:
    - port: {{ .Values.apigw.mgmtPort }}
      name: mgmt
    - port: {{ .Values.apigw.apiPort }}
      name: api

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.apigw.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Values.apigw.name | quote }}
spec:
  replicas: {{ .Values.apigw.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.apigw.name | quote }}
    spec:
      restartPolicy: {{ .Values.apigw.restartPolicy }}

      {{- if .Values.affinity.enabled }}
      affinity:
{{ include "affinity.core" . | indent 8 }}
{{ include "affinity.selfAntiAffinity" ( .Values.apigw.name | quote ) | indent 8 }}
      {{- end }}

      containers:
        - name: redis
          imagePullPolicy: {{ .Values.apigw.imagePullPolicy | quote }}
          image: redis:3.2

        - name: apigateway
          imagePullPolicy: {{ .Values.apigw.imagePullPolicy | quote }}
          image: {{ .Values.apigw.image | quote }}
          ports:
          - name: mgmt
            containerPort: {{ .Values.apigw.mgmtPort }}
          - name: api
            containerPort: {{ .Values.apigw.apiPort }}
          env:
          - name: "REDIS_HOST"
            value: "127.0.0.1"
          - name: "REDIS_PORT"
            value: "6379"
          - name: "PUBLIC_GATEWAY_URL"
            value: "https://{{ .Values.whisk.ingress.api_host }}"
