# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

---
apiVersion: v1
kind: Secret
metadata:
  name: whisk.auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  system: {{ .Values.whisk.auth.system | b64enc }}
  guest: {{ .Values.whisk.auth.guest | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: db.auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  db_username: {{ .Values.db.auth.username | b64enc }}
  db_password: {{ .Values.db.auth.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: docker.registry.auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  docker_registry_username: {{ .Values.docker.registry.username | b64enc }}
  docker_registry_password: {{ .Values.docker.registry.password | b64enc }}
