---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "controller_service_name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ template "controller_service_name" . }}
spec:
  selector:
    name: {{ template "controller_statefulset_name" . }}
  ports:
    - port: {{ template "controller_port" . }}
      targetPort: {{ template "controller_port" . }}
      name: http
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "controller_statefulset_name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ template "controller_statefulset_name" . }} 
spec:
  replicas: {{ .Values.controllerReplicaCount }}
  serviceName: {{ template "controller_service_name" . }}
  template:
    metadata:
      labels:
        name: {{ template "controller_statefulset_name" . }}
    spec:
      restartPolicy: Always

      {{- if .Values.affinity.enabled }}
      affinity:
{{ include "affinity.controlPlane" . | indent 8 }}
{{ include "affinity.selfAntiAffinity" ( include "controller_statefulset_name" . ) | indent 8 }}
      {{- end }}

      initContainers:
      # The controller must wait for kafka and couchdb to be ready before it starts
{{ include "readiness.waitForKafka" . | indent 6 }}
{{ include "readiness.waitForCouchDB" . | indent 6 }}

      containers:
      - name: {{ template "controller_statefulset_name" . }}
        imagePullPolicy: {{ .Values.controller.imagePullPolicy | quote }}
        image: {{ .Values.controller.image | quote }}
        command: ["/bin/bash", "-c", "COMPONENT_NAME=$(hostname | cut -d'-' -f2) /init.sh `hostname | cut -d'-' -f2`"]
        ports:
        - name: controller
          containerPort: {{ template "controller_port" . }}
        livenessProbe:
          httpGet:
            path: "/ping"
            port: {{ template "controller_port" . }}
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        env:
        - name: "PORT"
          value: {{ include "controller_port" . | quote }}

        # Loadbalancer options
        - name: "LOADBALANCER_INVOKERBUSYTHRESHOLD"
          value: "16"

        # action runtimes
        - name: "RUNTIMES_MANIFEST"
          value: {{ template "runtimes_manifest" . }}

        # this version is the day it is deployed and should be configured every time
        - name:  "WHISK_VERSION_DATE"
          value: "2017-01-01T00:00:00Z"
        # the buildno should be the docker image tag to use
        - name: "WHISK_VERSION_BUILDNO"
          value: "latest"
        - name: "WHISK_VERSION_NAME"
          value: ""

        # Java options
        - name: "JAVA_OPTS"
          value: "-Xmx2g"

        # Kafka properties
        - name: "KAFKA_HOSTS"
          value: {{ include "kafka_url_without_port" . }}:{{ .Values.kafka.port }}
        - name: "KAFKA_HOST_PORT"
          value: {{ .Values.kafka.port | quote }}

        # specific controller arguments
        - name: "CONTROLLER_OPTS"
          value: ""

        # properties for DB connection
{{ include "whisk.dbEnvVars" . | indent 8 }}

        - name: "LIMITS_ACTIONS_SEQUENCE_MAXLENGTH"
          value: {{ .Values.controller.limits.actionsSequenceMaxlength | quote }}
        - name: "LIMITS_TRIGGERS_FIRES_PERMINUTE"
          value: {{ .Values.controller.limits.triggersFiresPerminute | quote }}
        - name: "LIMITS_ACTIONS_INVOKES_PERMINUTE"
          value: {{ .Values.controller.limits.actionsInvokesPerminute | quote }}
        - name: "LIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM"
          value: {{ .Values.controller.limits.actionsInvokesConcurrentinsystem | quote }}
        - name: "LIMITS_ACTIONS_INVOKES_CONCURRENT"
          value: {{ .Values.controller.limits.actionsInvokesConcurrent | quote }}

        - name: "CONTROLLER_INSTANCES"
          value: {{ .Values.controller.replicaCount | quote }}
        - name: "CONTROLLER_LOCALBOOKKEEPING"
          value: {{ .Values.controller.localbookkeeping | quote }}
        - name: "AKKA_CLUSTER_SEED_NODES"
          value: {{ .Values.controller.seedNodes | quote }}
        - name: "CONTROLLER_HA"
          value: {{ .Values.controller.HA | quote }}
        - name: "CONFIG_akka_actor_provider"
          value: "cluster"
