# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: broker
    port: {{ .Values.kafka.port }}
  selector:
    app: {{ .Values.kafka.name | quote }}

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.kafka.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  name: {{ .Values.kafka.name | quote }}
  replicas: {{ .Values.kafka.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name | quote }}
    spec:
      {{- if .Values.affinity.enabled }}
      affinity:
{{ include "affinity.core" . | indent 8 }}
{{ include "affinity.selfAntiAffinity" ( .Values.kafka.name | quote ) | indent 8 }}
      {{- end }}

      initContainers:
{{ include "readiness.waitForZookeeper" . | indent 6 }}

      containers:
      - name: {{ .Values.kafka.name | quote }}
        image: {{ .Values.kafka.image | quote }}
        imagePullPolicy: {{ .Values.kafka.imagePullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.kafka.port }}
          name: kafka
        env:
        - name: "KAFKA_BROKER_ID"
          value: "0"
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: {{ .Values.kafka.name | quote }}
        - name: "KAFKA_ADVERTISED_PORT"
          value: "{{ .Values.kafka.port }}"
        - name: "KAFKA_HOST_NAME"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "KAFKA_PORT"
          value: "{{ .Values.kafka.port }}"

        # zookeeper info
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "{{ include "zookeeper_host" . }}:{{ .Values.zookeeper.port }}"
