# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Values.zookeeper.name | quote }}
spec:
  selector:
    name: {{ .Values.zookeeper.name | quote }}
  ports:
    - port: {{ .Values.zookeeper.port }}
      name: "zookeeper"
    - port: {{ .Values.zookeeper.serverPort }}
      name: "server"
    - port: {{ .Values.zookeeper.leaderElectionPort }}
      name: "leader-election"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name | quote }}
  namespace: {{ .Release.Namespace | quote}}
  labels:
    name: {{ .Values.zookeeper.name | quote }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.zookeeper.name | quote }}
    spec:
      restartPolicy: {{ .Values.zookeeper.restartPolicy | quote }}

      {{- if .Values.affinity.enabled }}
      affinity:
{{ include "affinity.core" . | indent 8 }}
{{ include "affinity.selfAntiAffinity" ( .Values.zookeeper.name | quote ) | indent 8 }}
      {{- end }}

      containers:
      - name: {{ .Values.zookeeper.name | quote }}
        image: {{ .Values.zookeeper.image | quote }}
        imagePullPolicy: {{ .Values.zookeeper.imagePullPolicy | quote }}
        ports:
        - name: zookeeper
          containerPort: {{ .Values.zookeeper.port }}
        - name: server
          containerPort: {{ .Values.zookeeper.serverPort }}
        - name: leader-election
          containerPort: {{ .Values.zookeeper.leaderElectionPort }}
