# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.cloudantprovider.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: cloudantprovider
spec:
  replicas: {{ .Values.cloudantprovider.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.cloudantprovider.name | quote }}
    spec:
      restartPolicy: {{ .Values.cloudantprovider.restartPolicy }}
      volumes:
        - name: cloudant-logs
          persistentVolumeClaim:
            claimName: {{ .Values.cloudantprovider.persistence.pvcName | quote }}
      containers:
      - name: {{ .Values.cloudantprovider.name | quote }}
        imagePullPolicy: {{ .Values.cloudantprovider.imagePullPolicy | quote }}
        image: {{ .Values.cloudantprovider.image | quote }}
        ports:
        - name: cludntprovider
          containerPort: {{ .Values.cloudantprovider.apiPort }}
        env:
        - name: "DB_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_protocol
        - name: "DB_HOST"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_host_port
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_username
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_password
        - name: "DB_PREFIX"
          value: "{{- .Values.cloudantprovider.dbPrefix -}}"
        - name: "ROUTER_HOST"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
        - name: "ENDPOINT_AUTH"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
        volumeMounts:
          - name: cloudant-logs
            mountPath: /logs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cloudantprovider.persistence.pvcName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.cloudantprovider.persistence.storageClass }}
  accessModes:
    - {{ .Values.cloudantprovider.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cloudantprovider.persistence.size }}
