# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---

# Playbook to prefetch runtime action images from a docker registry for an invoker node.

- hosts: localhost
  vars:
    docker_pull_retries: 10
    docker_pull_delay: 10
    docker_registry:
    runtimesManifest: "{{ lookup('env', 'RUNTIMES_MANIFEST') | from_json }}"
    dip: "{{ lookup('env', 'DEFAULT_IMAGE_PREFIX') }}"
    defaultImagePrefix: "{{ dip if dip != '' else 'openwhisk'}}"
    dit: "{{ lookup('env', 'DEFAULT_IMAGE_TAG') }}"
    defaultImageTag: "{{ dit if dit != '' else 'latest' }}"

  tasks:
    - name: docker login
      docker_login:
        registry: "{{ docker_registry }}"
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
      when: docker_registry != "" and docker_registry_password is defined

    - name: "pull runtime action images with tag {{defaultImageTag}}"
      shell: "docker pull {{docker_registry}}{{defaultImagePrefix}}/{{item}}:{{defaultImageTag}}"
      with_items: "{{ runtimesManifest.runtimes.values() | sum(start=[]) | selectattr('deprecated', 'equalto',false)  | map(attribute='image.name') | list | unique }}"
      when: docker_registry != ""
      retries: "{{ docker_pull_retries }}"
      delay: "{{ docker_pull_delay }}"

    - name: "pull blackboxes action images with tag {{defaultImageTag}}"
      shell: "docker pull {{docker_registry}}{{defaultImagePrefix}}/{{item.name}}:{{defaultImageTag}}"
      with_items:
        - "{{ runtimesManifest.blackboxes }}"
      when: docker_registry != ""
      retries: "{{ docker_pull_retries }}"
      delay: "{{ docker_pull_delay }}"
