---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: controller
  namespace: openwhisk
  labels:
    name: controller
spec:
  replicas: 2
  serviceName: "controller"
  template:
    metadata:
      labels:
        name: controller
    spec:
      restartPolicy: Always

      containers:
      - name: controller
        imagePullPolicy: Always
        image: openwhisk/controller
        command: ["/bin/bash", "-c", "COMPONENT_NAME=$(hostname | cut -d'-' -f2) /init.sh `hostname | cut -d'-' -f2`"]
        ports:
        - name: controller
          containerPort: 8080
        env:
        # Properties for controller HA configuration
        # Must change these if changing number of replicas
        - name: "CONTROLLER_LOCALBOOKKEEPING"
          value: "FALSE"
        - name: "CONTROLLER_HA"
          value: "TRUE"
        - name: "CONTROLLER_INSTANCES"
          value: "2"
        - name: "AKKA_CLUSTER_SEED_NODES"
          value: "controller-0.controller.openwhisk controller-1.controller.openwhisk"
        - name: "CONFIG_akka_actor_provider"
          value: "cluster"

        # extra JVM arguments
        - name: "JAVA_OPTS"
          valueFrom:
            configMapKeyRef:
              name: controller.config
              key: java_opts

        # extra controller arguments
        - name: "CONTROLLER_OPTS"
          valueFrom:
            configMapKeyRef:
              name: controller.config
              key: controller_opts

        # action runtimes
        - name: "RUNTIMES_MANIFEST"
          valueFrom:
            configMapKeyRef:
              name: whisk.runtimes
              key: runtimes

        # deployment version information
        - name:  "WHISK_VERSION_NAME"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_version_name
        - name:  "WHISK_VERSION_DATE"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_version_date
        - name: "WHISK_VERSION_BUILDNO"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_version_tag

        # specify limits
        - name: "LIMITS_ACTIONS_INVOKES_PERMINUTE"
          valueFrom:
            configMapKeyRef:
              name: whisk.limits
              key: actions_invokes_perMinute
        - name: "LIMITS_ACTIONS_INVOKES_CONCURRENT"
          valueFrom:
            configMapKeyRef:
              name: whisk.limits
              key: actions_invokes_concurrent
        - name: "LIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM"
          valueFrom:
            configMapKeyRef:
              name: whisk.limits
              key: actions_invokes_concurrentInSystem
        - name: "LIMITS_TRIGGERS_FIRES_PERMINUTE"
          valueFrom:
            configMapKeyRef:
              name: whisk.limits
              key: triggers_fires_perMinute
        - name: "LIMITS_ACTIONS_SEQUENCE_MAXLENGTH"
          valueFrom:
            configMapKeyRef:
              name: whisk.limits
              key: actions_sequence_maxLength

        # properties for Kafka connection
        - name: "KAFKA_HOSTS"
          value: "$(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT_KAFKA)"

        # properties for DB connection
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_username
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_password
        - name:  "DB_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_protocol
        - name: "DB_HOST"
          value: "$(COUCHDB_SERVICE_HOST)"
        - name: "DB_PORT"
          value: "$(COUCHDB_SERVICE_PORT_COUCHDB)"
        - name: "DB_PROVIDER"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_provider
        - name: "DB_WHISK_ACTIVATIONS"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_whisk_activations
        - name: "DB_WHISK_ACTIONS"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_whisk_actions
        - name: "DB_WHISK_AUTHS"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_whisk_auths

        # must match port used in livenessProbe below
        - name: "PORT"
          value: "8080"

        livenessProbe:
          httpGet:
            path: "/ping"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
