---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: openwhisk
  labels:
    name: controller
spec:
  selector:
    name: controller
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: controller
  namespace: openwhisk
  labels:
    name: controller
spec:
  replicas: 2
  serviceName: "controller"
  template:
    metadata:
      labels:
        name: controller
    spec:
      restartPolicy: Always

      containers:
      - name: controller
        imagePullPolicy: Always
        image: openwhisk/controller
        command: ["/bin/bash", "-c", "COMPONENT_NAME=$(hostname | cut -d'-' -f2) /init.sh `hostname | cut -d'-' -f2`"]
        ports:
        - name: controller
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: "/ping"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        env:
        - name: "PORT"
          value: "8080"

        # This needs to stay up to date with the lates runtime in Ansible Groupvars
        - name: "RUNTIMES_MANIFEST"
          value: '{ "defaultImagePrefix": "openwhisk", "defaultImageTag": "latest", "runtimes": { "nodejs": [ { "kind": "nodejs", "image": { "name": "nodejsaction" }, "deprecated": true }, { "kind": "nodejs:6", "default": true, "image": { "name": "nodejs6action" }, "deprecated": false } ], "python": [ { "kind": "python", "image": { "name": "python2action" }, "deprecated": false }, { "kind": "python:2", "default": true, "image": { "name": "python2action" }, "deprecated": false }, { "kind": "python:3", "image": { "name": "python3action" }, "deprecated": false } ], "swift": [ { "kind": "swift", "image": { "name": "swiftaction" }, "deprecated": true }, { "kind": "swift:3", "image": { "name": "swift3action" }, "deprecated": true }, { "kind": "swift:3.1.1", "default": true, "image": { "name": "action-swift-v3.1.1" }, "deprecated": false } ], "java": [ { "kind": "java", "default": true, "image": { "name": "java8action" }, "deprecated": false, "attached": { "attachmentName": "jarfile", "attachmentType": "application/java-archive" }, "sentinelledLogs": false, "requireMain": true } ] }, "blackboxes": [ { "name": "dockerskeleton" } ] }'

        # this version is the day it is deployed and should be configured every time
        - name:  "WHISK_VERSION_DATE"
          value: "2017-01-01T00:00:00Z"
        # the buildno should be the docker image tag to use
        - name: "WHISK_VERSION_BUILDNO"
          value: "latest"

        # Java options
        - name: "JAVA_OPTS"
          value: "-Xmx2g"

        # Kafka properties
        - name: "KAFKA_HOSTS"
          value: "$(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT_KAFKA)"

        # specific controller arguments
        - name: "CONTROLLER_INSTANCES"
          value: "2"
        - name: "CONTROLLER_OPTS"
          value: ""
        - name: "DEFAULTLIMITS_ACTIONS_INVOKES_PERMINUTE"
          value: "120"
        - name: "DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENT"
          value: "100"
        - name: "DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM"
          value: "500"
        - name: "DEFAULTLIMITS_ACTIONS_SEQUENCE_MAXLENGTH"
          value: "50"
        - name: "DEFAULTLIMITS_TRIGGERS_FIRES_PERMINUTE"
          value: "60"
        - name: "LIMITS_ACTIONS_SEQUENCE_MAXLENGTH"
          value: "50"
        - name: "LIMITS_TRIGGERS_FIRES_PERMINUTE"
          value: "60"
        - name: "LIMITS_ACTIONS_INVOKES_PERMINUTE"
          value: "60"
        - name: "LIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM"
          value: "5000"
        - name: "LIMITS_ACTIONS_INVOKES_CONCURRENT"
          value: "30"
        - name: "CONTROLLER_LOCALBOOKKEEPING"
          value: "FALSE"
        - name: "CONTROLLER_HA"
          value: "TRUE"
        - name: "AKKA_CLUSTER_SEED_NODES"
          value: "controller-0.controller.openwhisk controller-1.controller.openwhisk"
        - name: "CONFIG_akka_actor_provider"
          value: "cluster"

        # properties for DB connection
        - name: "DB_USERNAME"
          value: "whisk_admin"
        - name: "DB_PASSWORD"
          value: "some_passw0rd"
        - name:  "DB_PROTOCOL"
          value: "http"
        - name: "DB_HOST"
          value: "$(COUCHDB_SERVICE_HOST)"
        - name: "DB_PORT"
          value: "$(COUCHDB_SERVICE_PORT_COUCHDB)"
        - name: "DB_PROVIDER"
          value: "CouchDB"
        - name: "DB_WHISK_ACTIONS_DDOC"
          value: "whisks.v2"
        - name: "DB_WHISK_ACTIVATIONS_DDOC"
          value: "whisks.v2"
        - name: "DB_WHISK_ACTIVATIONS_FILTER_DDOC"
          value: "whisks-filters.v2"
        - name: "DB_WHISK_ACTIVATIONS"
          value: "test_activations"
        - name: "DB_WHISK_ACTIONS"
          value: "test_whisks"
        - name: "DB_WHISK_AUTHS"
          value: "test_subjects"
