apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis_service_name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ template "redis_service_name" . }}
spec:
  selector:
    name: {{ template "redis_deployment_name" . }}
  ports:
    - port: {{ template "redis_port" . }}
      targetPort: {{ template "redis_port" . }}
      name: redis