---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: openwhisk
  labels:
    name: nginx
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https-api
    - port: 8443
      targetPort: 8443
      name: https-admin

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: openwhisk
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      restartPolicy: Always
      volumes:
      - name: nginx-certs
        secret:
          secretName: nginx
      - name: nginx-conf
        configMap:
          name: nginx
      - name: logs
        emptyDir: {}
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: danlavine/whisk_nginx
        ports:
        - name: http
          containerPort: 80
        - name: http-api
          containerPort: 443
        - name: https-admin
          containerPort: 8443
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
        - name: nginx-certs
          mountPath: "/etc/nginx/certs"
        - name: logs
          mountPath: "/logs"
