---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: openwhisk
  labels:
    name: controller
spec:
  selector:
    name: controller
  ports:
    - port: 8080
      targetPort: 8080
      name: controller
