---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb
  namespace: openwhisk
  labels:
    name: couchdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      restartPolicy: Always

      volumes:
      - name: couchdbconfig
        secret:
          secretName: couchdb-config
      - name: couchdbdata
        persistentVolumeClaim:
          claimName: openwhisk-couchdb

      containers:
      - name: couchdb
        imagePullPolicy: IfNotPresent
        image: couchdb:1.6
        ports:
        - name: couchdb
          containerPort: 5984
        volumeMounts:
        - name: couchdbconfig
          mountPath: /usr/local/etc/couchdb/local.d/
        - name: couchdbdata
          mountPath: /usr/local/var/lib/couchdb
