apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka_service_name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: broker
    port: {{ template "kafka_port" . }} 
  clusterIP: None
  selector:
    app: {{ template "kafka_statefulset_name" . }}
