# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafkaprovider.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: nginx
spec:
  replicas: {{ .Values.kafkaprovider.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.kafkaprovider.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.kafkaprovider.name | quote }}
    spec:
      restartPolicy: {{ .Values.kafkaprovider.restartPolicy }}
      containers:
      - name: {{ .Values.kafkaprovider.name | quote }}
        imagePullPolicy: {{ .Values.kafkaprovider.imagePullPolicy | quote }}
        image: {{ .Values.kafkaprovider.image | quote }}
        ports:
        - name: kafkaprovider
          containerPort: {{ .Values.kafkaprovider.apiPort }}
        env:
        {{- if .Values.kafkaprovider.db.external }}
        # Config database using the external instance
        - name: "DB_URL"
          value: {{ .Values.kafkaprovider.db.protocol }}://{{ .Values.kafkaprovider.db.host }}:{{ .Values.kafkaprovider.db.port }}
        - name: "DB_USER"
          value: {{ .Values.kafkaprovider.db.username | quote }}
        - name: "DB_PASS"
          value: {{ .Values.kafkaprovider.db.password | quote }}
        {{- else }}
        # Config database using the same openwhisk cloudant instance
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_url
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_username
        - name: "DB_PASS"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_password
        {{- end }}
        - name: "DB_PREFIX"
          value: "{{- .Values.kafkaprovider.db.prefix -}}"
        - name: "LOCAL_DEV"
          value: "true"
        - name: "ROUTER_HOST"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
        - name: "ENDPOINT_AUTH"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
