# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.kafkaprovider.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: nginx
spec:
  replicas: {{ .Values.kafkaprovider.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.kafkaprovider.name | quote }}
    spec:
      restartPolicy: {{ .Values.kafkaprovider.restartPolicy }}
      containers:
      - name: {{ .Values.kafkaprovider.name | quote }}
        imagePullPolicy: {{ .Values.kafkaprovider.imagePullPolicy | quote }}
        image: {{ .Values.kafkaprovider.image | quote }}
        ports:
        - name: kafkaprovider
          containerPort: {{ .Values.kafkaprovider.apiPort }}
        env:
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_url
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_username
        - name: "DB_PASS"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_password
        - name: "DB_PREFIX"
          value: "{{- .Values.kafkaprovider.dbPrefix -}}"
        - name: "LOCAL_DEV"
          value: "true"
        - name: "ROUTER_HOST"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
        - name: "ENDPOINT_AUTH"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
