---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: openwhisk
  labels:
    name: redis
spec:
  selector:
    name: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: openwhisk
  labels:
    name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      restartPolicy: Always

      containers:
      - name: redis
        imagePullPolicy: IfNotPresent
        image: redis:3.2
        ports:
        - name: redis
          containerPort: 6379
