# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# Kafka provider configurations
kafkaprovider:
  name: "kafkaprovider"
  image: "openwhisk/kafkaprovider:latest"
  # NOTE: setting replicaCount > 1 has not been tested and may not work
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  apiPort: 8080
  db:
    external: false
    prefix: "kp"
    # Add below values if you are using external couchdb instance
    # host: "10.10.10.10"
    # port: 5984
    # protocol: "http"
    # username: "admin"
    # password: "secret"

# Images used to run auxillary tasks/jobs
utility:
  scriptRunnerImage: "openwhisk/script-runner:latest"
  imagePullPolicy: "Always"
