# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# Alarm provider configurations
cloudantprovider:
  name: "cloudantprovider"
  image: "openwhisk/cloudantprovider:latest"
  # NOTE: replicaCount > 1 doesn't work because of the PVC
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  apiPort: 8080
  db:
    external: false
    prefix: "cldt"
    # Add below values if you are using external instance
    # host: "10.10.10.10"
    # port: 5984
    # protocol: "http"
    # username: "admin"
    # password: "secret"
  persistence:
    pvcName: cludntprovider-pvc
    size: 1Gi
    storageClass: default
    accessMode: ReadWriteOnce
