# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{- if ne .Values.alarmprovider.persistence.storageClass "none" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.alarmprovider.persistence.pvcName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.alarmprovider.persistence.storageClass }}
  accessModes:
    - {{ .Values.alarmprovider.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.alarmprovider.persistence.size }}
{{- end }}
