# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alarmprovider.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: alarmprovider
spec:
  replicas: {{ .Values.alarmprovider.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.alarmprovider.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.alarmprovider.name | quote }}
    spec:
      restartPolicy: {{ .Values.alarmprovider.restartPolicy }}
      volumes:
        - name: alarm-logs
{{- if ne .Values.alarmprovider.persistence.storageClass "none" }}
          persistentVolumeClaim:
            claimName: {{ .Values.alarmprovider.persistence.pvcName | quote }}
{{- else }}
          emptyDir: {}
{{- end }}
      containers:
      - name: {{ .Values.alarmprovider.name | quote }}
        imagePullPolicy: {{ .Values.alarmprovider.imagePullPolicy | quote }}
        image: {{ .Values.alarmprovider.image | quote }}
        ports:
        - name: alarmprovider
          containerPort: {{ .Values.alarmprovider.apiPort }}
        env:
        {{- if .Values.alarmprovider.db.external }}
        # Config database using the external instance
        - name: "DB_PROTOCOL"
          value: {{ .Values.alarmprovider.db.protocol | quote }}
        - name: "DB_HOST"
          value: "{{ .Values.alarmprovider.db.host }}:{{ .Values.alarmprovider.db.port }}"
        - name: "DB_USERNAME"
          value: {{ .Values.alarmprovider.db.username | quote }}
        - name: "DB_PASSWORD"
          value: {{ .Values.alarmprovider.db.password | quote }}
        {{- else }}
        - name: "DB_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_protocol
        - name: "DB_HOST"
          valueFrom:
            configMapKeyRef:
              name: db.config
              key: db_host_port
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_username
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_password
        {{- end }}
        - name: "DB_PREFIX"
          value: "{{- .Values.alarmprovider.db.prefix -}}"
        - name: "ROUTER_HOST"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
        - name: "ENDPOINT_AUTH"
          valueFrom:
            configMapKeyRef:
              name: whisk.config
              key: whisk_api_host_nameAndPort
        volumeMounts:
          - name: alarm-logs
            mountPath: /logs
