apiVersion: v1
description: A Helm chart to deploy Apache OpenWhisk for Kubernetes
name: openwhisk
version: 0.1.0
keywords:
  - Apache OpenWhisk
maintainers:
  - name: Apache OpenWhisk committers
    email: dev@openwhisk.apache.org
