# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
description: A Helm chart to deploy Apache OpenWhisk for Kubernetes
name: openwhisk
version: 0.1.0
keywords:
  - Apache OpenWhisk
maintainers:
  - name: Apache OpenWhisk committers
    email: dev@openwhisk.apache.org
