# Default values for OpenWhisk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overall system configuration
whisk:
  # You must provide these ingress values when deploying the chart
  ingress:
    api_host: nil
    apigw_url: nil
  # Production deployments _MUST_ override these default auth values
  auth:
    system: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
    guest: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
  versions:
    cli: "latest"
  systemNameSpace: "/whisk.system"

travis: false

# zookeeper configurations
zookeeper:
  deploymentName: "zookeeper"
  serviceName: "zookeeper"
  replicaCount: 1
  restartPolicy: "Always"
  containerName: "zookeeper"
  image: "zookeeper:3.4"
  imagePullPolicy: "IfNotPresent"
  port: 2181
  serverPort: 2888
  leaderElectionPort: 3888

# kafka configurations
kafka:
  serviceName: "kafka"
  statefulsetName: "kafka"
  replicaCount: 1
  image: "wurstmeister/kafka:0.11.0.1"
  imagePullPolicy: "IfNotPresent"
  port: 9092

# Database configuration
db:
  deploymentName: "couchdb"
  serviceName: "couchdb"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  image: "openwhisk/kube-couchdb"
  port: 5984
  auth:
    username: "whisk_admin"
    password: "some_passw0rd"
  dbPrefix: "test_"
  activationsTable: "test_activations"
  actionsTable: "test_whisks"
  authsTable: "test_subjects"
  persistence:
    enabled: false
    pvcName: couchdb-pvc
    size: 8Gi
    storageClass: CouchDBSC 
    accessMode: ReadWriteOnce

# Nginx configurations
nginx:
  secretName: "nginx"
  configmapName: "nginx"
  deploymentName: "nginx"
  replicaCount: 1
  image: "nginx:1.11"
  imagePullPolicy: "IfNotPresent"
  httpPort: 80
  httpNodePort: 31000
  httpsPort: 443
  httpsNodePort: 31001
  httpsAdminPort: 8443
  httpsAdminNodePort: 31002
  serviceName: "nginx"

# Controller configurations
controller:
  serviceName: "controller"
  statefulSetName: "controller"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  image: "openwhisk/controller"
  port: 8080
  limits:
    actionsSequenceMaxlength: 50
    triggersFiresPerminute: 60
    actionsInvokesPerminute: 60
    actionsInvokesConcurrentinsystem: 5000
    actionsInvokesConcurrent: 30
  localbookkeeping: true
  seedNodes: "[]"
  HA: false

# Invoker configurations
invokerDeploymentName: "invoker"
invokerReplicasetCount: 1
invokerImagePullPolicy: "IfNotPresent"
invokerImage: "openwhisk/invoker"
invokerOptions: ""

# API Gateway configurations
apigatewayImagePullPolicy: "IfNotPresent"
apigatewayImage: "openwhisk/apigateway"
apigatewayReplicaCount: 1
apigw:
  deploymentName: "apigateway"
  serviceName: "apigateway"
  apiPort: 9000
  mgmtPort: 8080

# Resolve the pod/node affinity for invoker, controller and other components.
affinity:
  enabled: true
  invokerNodeLabel: invoker
  controlPlaneNodeLabel: control-plane
