# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# Default values for OpenWhisk.

# Overall system configuration
whisk:
  ingress:
    name: "ow-ingress"
    # You _MUST_ provide a value for whisk.ingress.api_host_name and api_host_port when deploying the chart
    api_host_name: nil
    api_host_port: nil
    api_host_proto: "https"
  # Production deployments _MUST_ override these default auth values
  auth:
    system: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
    guest: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
  versions:
    name: "OpenWhisk"
    tag: "latest"
    cli: "latest"
  systemNameSpace: "/whisk.system"
  runtimes: "runtimes.json"

# Docker registry
docker:
  image:
    prefix: "openwhisk"
    tag: "latest"
  registry:
    name: ""
    username: ""
    password: ""

# zookeeper configurations
zookeeper:
  name: "zookeeper"
  image: "zookeeper:3.4"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  port: 2181
  serverPort: 2888
  leaderElectionPort: 3888
  persistence:
    enabled: false
    pvcName: zookeeper-pvc
    size: 2Gi
    storageClass: default
    accessMode: ReadWriteOnce

# kafka configurations
kafka:
  name: "kafka"
  image: "wurstmeister/kafka:0.11.0.1"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  port: 9092
  persistence:
    enabled: false
    pvcName: kafka-pvc
    size: 2Gi
    storageClass: default
    accessMode: ReadWriteOnce

# Database configuration
db:
  name: "couchdb"
  image: "openwhisk/kube-couchdb:latest"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  port: 5984
  provider: "CouchDB"
  protocol: "http"
  auth:
    username: "whisk_admin"
    password: "some_passw0rd"
  dbPrefix: "test_"
  activationsTable: "test_activations"
  actionsTable: "test_whisks"
  authsTable: "test_subjects"
  persistence:
    enabled: false
    pvcName: couchdb-pvc
    size: 8Gi
    storageClass: default
    accessMode: ReadWriteOnce

# Nginx configurations
nginx:
  name: "nginx"
  image: "nginx:1.11"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  httpPort: 80
  httpsPort: 443
  httpsAdminPort: 8443

# Controller configurations
controller:
  name: "controller"
  image: "openwhisk/controller:latest"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  port: 8080
  options: ""
  jvmHeapMB: "1024"
  jvmOptions: ""
  limits:
    actionsSequenceMaxlength: 50
    triggersFiresPerminute: 60
    actionsInvokesPerminute: 60
    actionsInvokesConcurrentinsystem: 5000
    actionsInvokesConcurrent: 30

# Invoker configurations
invoker:
  name: "invoker"
  image: "openwhisk/invoker:latest"
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  port: 8080
  pullRuntimesImage: "openwhisk/kube-docker-pull:latest"
  options: ""
  jvmHeapMB: "512"
  jvmOptions: ""
  containerFactory:
    useRunc: false
    impl: "docker"
    kubernetes:
      replicaCount: 1
      agent:
        name: "invoker-agent"
        image: "openwhisk/kube-invoker-agent:latest"
        enabled: false
        port: 3233
  containerNetwork: "bridge"
  containerPool:
    numcore: 2
    coreshare: 4
  busyThreshold: 8

# API Gateway configurations
apigw:
  name: "apigateway"
  image: "openwhisk/apigateway:latest"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  apiPort: 9000
  mgmtPort: 8080

# Redis (used by apigatewy)
redis:
  name: "redis"
  image: "redis:3.2"
  replicaCount: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: "Always"
  port: 6379
  persistence:
    enabled: false
    pvcName: redis-pvc
    size: 256Mi
    storageClass: default
    accessMode: ReadWriteOnce

# Resolve the pod/node affinity for invoker, controller and other components.
affinity:
  enabled: true
  coreNodeLabel: core
  edgeNodeLabel: edge
  invokerNodeLabel: invoker
  providerNodeLabel: provider
