apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "zookeeper_deployment_name" . }}
  namespace: {{ .Release.Namespace | default "openwhisk" | quote}}
  labels:
    name: {{ template "zookeeper_deployment_name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1}}
  template:
    metadata:
      labels:
        name: {{ template "zookeeper_deployment_name" . }}
    spec:
      restartPolicy: {{ .Values.restartPolicy | default "Always" | quote }}

      {{- if .Values.global.affinity.enabled }}
      affinity:
{{ include "affinity.controlPlane" . | indent 8 }}
{{ include "affinity.selfAntiAffinity" ( include "zookeeper_deployment_name" . ) | indent 8 }}
      {{- end }}

      containers:
      - name: {{ .Values.containerName | default "zookeeper" | quote }}
        image: {{ .Values.image | default "zookeeper:3.4" | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" | quote }}
        ports:
        - name: zookeeper
          containerPort: {{ template "zookeeper_port" . }}
        - name: server
          containerPort: {{ template "zookeeper_server_port" . }}
        - name: leader-election
          containerPort: {{ template "zookeeper_leader_election_port" . }}
